name: rust-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install libudev
      run: sudo apt-get install libudev-dev pkg-config
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
